package com.bizwink.persistence;

import com.bizwink.po.Jobinfo;
import com.bizwink.po.JobinfoExample;
import java.math.BigDecimal;

public interface JobinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_JOBINFO
     *
     * @mbggenerated
     */
    int countByExample(JobinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_JOBINFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_JOBINFO
     *
     * @mbggenerated
     */
    int insert(Jobinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_JOBINFO
     *
     * @mbggenerated
     */
    int insertSelective(Jobinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_JOBINFO
     *
     * @mbggenerated
     */
    Jobinfo selectByPrimaryKey(BigDecimal ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_JOBINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Jobinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_JOBINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Jobinfo record);
}