package com.bizwink.po;

import java.math.BigDecimal;
import java.util.Date;

public class Jobinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.ID
     *
     * @mbggenerated
     */
    private BigDecimal ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.COMPANYID
     *
     * @mbggenerated
     */
    private String COMPANYID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.POSTID
     *
     * @mbggenerated
     */
    private String POSTID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.FIRSTNAME
     *
     * @mbggenerated
     */
    private String FIRSTNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.SENDNAME
     *
     * @mbggenerated
     */
    private String SENDNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.GENDER
     *
     * @mbggenerated
     */
    private String GENDER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.NATIONALITY
     *
     * @mbggenerated
     */
    private String NATIONALITY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.AGE
     *
     * @mbggenerated
     */
    private String AGE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.MARRAGE
     *
     * @mbggenerated
     */
    private BigDecimal MARRAGE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.BIRTHDAY
     *
     * @mbggenerated
     */
    private String BIRTHDAY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.BIRTHPLACE
     *
     * @mbggenerated
     */
    private String BIRTHPLACE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.PHOTOPATH
     *
     * @mbggenerated
     */
    private String PHOTOPATH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.PHOTOOLDNAME
     *
     * @mbggenerated
     */
    private String PHOTOOLDNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.ACCONTPLACE
     *
     * @mbggenerated
     */
    private String ACCONTPLACE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.HOMEADDRESS
     *
     * @mbggenerated
     */
    private String HOMEADDRESS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.LIVEADDRESS
     *
     * @mbggenerated
     */
    private String LIVEADDRESS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.EDUCATIONALCATEGORIE
     *
     * @mbggenerated
     */
    private String EDUCATIONALCATEGORIE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.EDUCATION
     *
     * @mbggenerated
     */
    private String EDUCATION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.MAJORSUBJECTS1
     *
     * @mbggenerated
     */
    private String MAJORSUBJECTS1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.MAJORSUBJECTS2
     *
     * @mbggenerated
     */
    private String MAJORSUBJECTS2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.PROFESSIONAL
     *
     * @mbggenerated
     */
    private String PROFESSIONAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.CERTIFICATE
     *
     * @mbggenerated
     */
    private String CERTIFICATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.CBGNTIME
     *
     * @mbggenerated
     */
    private String CBGNTIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.CENDTIME
     *
     * @mbggenerated
     */
    private String CENDTIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.GRADUATESCHOOL
     *
     * @mbggenerated
     */
    private String GRADUATESCHOOL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.DOCUMENTSTYPE
     *
     * @mbggenerated
     */
    private String DOCUMENTSTYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.DOCUMENTSNUM1
     *
     * @mbggenerated
     */
    private String DOCUMENTSNUM1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.TITLEBGNTIME
     *
     * @mbggenerated
     */
    private String TITLEBGNTIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.TITLENAME
     *
     * @mbggenerated
     */
    private String TITLENAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.GRADE
     *
     * @mbggenerated
     */
    private String GRADE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.WORKBGNTIME1
     *
     * @mbggenerated
     */
    private String WORKBGNTIME1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.WORKENDTIME1
     *
     * @mbggenerated
     */
    private String WORKENDTIME1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.EMPLOYER1
     *
     * @mbggenerated
     */
    private String EMPLOYER1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.POST1
     *
     * @mbggenerated
     */
    private String POST1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.CITY1
     *
     * @mbggenerated
     */
    private String CITY1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.MOBILE
     *
     * @mbggenerated
     */
    private String MOBILE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.PHONE
     *
     * @mbggenerated
     */
    private String PHONE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.EMAIL
     *
     * @mbggenerated
     */
    private String EMAIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.CREATEDATE
     *
     * @mbggenerated
     */
    private Date CREATEDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.MAJOR1
     *
     * @mbggenerated
     */
    private String MAJOR1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.MAJOR2
     *
     * @mbggenerated
     */
    private String MAJOR2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.DOCUMENTSNUM2
     *
     * @mbggenerated
     */
    private String DOCUMENTSNUM2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.DOCUMENTSNUM3
     *
     * @mbggenerated
     */
    private String DOCUMENTSNUM3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.DOCUMENTSNUM4
     *
     * @mbggenerated
     */
    private String DOCUMENTSNUM4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.WORKBGNTIME2
     *
     * @mbggenerated
     */
    private String WORKBGNTIME2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.WORKENDTIME2
     *
     * @mbggenerated
     */
    private String WORKENDTIME2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.EMPLOYER2
     *
     * @mbggenerated
     */
    private String EMPLOYER2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.POST2
     *
     * @mbggenerated
     */
    private String POST2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.CITY2
     *
     * @mbggenerated
     */
    private String CITY2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.WORKBGNTIME3
     *
     * @mbggenerated
     */
    private String WORKBGNTIME3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.WORKENDTIME3
     *
     * @mbggenerated
     */
    private String WORKENDTIME3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.EMPLOYER3
     *
     * @mbggenerated
     */
    private String EMPLOYER3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.POST3
     *
     * @mbggenerated
     */
    private String POST3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.CITY3
     *
     * @mbggenerated
     */
    private String CITY3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_JOBINFO.SUBTITLENAME
     *
     * @mbggenerated
     */
    private String SUBTITLENAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.ID
     *
     * @return the value of TBL_JOBINFO.ID
     *
     * @mbggenerated
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.ID
     *
     * @param ID the value for TBL_JOBINFO.ID
     *
     * @mbggenerated
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.COMPANYID
     *
     * @return the value of TBL_JOBINFO.COMPANYID
     *
     * @mbggenerated
     */
    public String getCOMPANYID() {
        return COMPANYID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.COMPANYID
     *
     * @param COMPANYID the value for TBL_JOBINFO.COMPANYID
     *
     * @mbggenerated
     */
    public void setCOMPANYID(String COMPANYID) {
        this.COMPANYID = COMPANYID == null ? null : COMPANYID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.POSTID
     *
     * @return the value of TBL_JOBINFO.POSTID
     *
     * @mbggenerated
     */
    public String getPOSTID() {
        return POSTID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.POSTID
     *
     * @param POSTID the value for TBL_JOBINFO.POSTID
     *
     * @mbggenerated
     */
    public void setPOSTID(String POSTID) {
        this.POSTID = POSTID == null ? null : POSTID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.FIRSTNAME
     *
     * @return the value of TBL_JOBINFO.FIRSTNAME
     *
     * @mbggenerated
     */
    public String getFIRSTNAME() {
        return FIRSTNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.FIRSTNAME
     *
     * @param FIRSTNAME the value for TBL_JOBINFO.FIRSTNAME
     *
     * @mbggenerated
     */
    public void setFIRSTNAME(String FIRSTNAME) {
        this.FIRSTNAME = FIRSTNAME == null ? null : FIRSTNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.SENDNAME
     *
     * @return the value of TBL_JOBINFO.SENDNAME
     *
     * @mbggenerated
     */
    public String getSENDNAME() {
        return SENDNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.SENDNAME
     *
     * @param SENDNAME the value for TBL_JOBINFO.SENDNAME
     *
     * @mbggenerated
     */
    public void setSENDNAME(String SENDNAME) {
        this.SENDNAME = SENDNAME == null ? null : SENDNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.GENDER
     *
     * @return the value of TBL_JOBINFO.GENDER
     *
     * @mbggenerated
     */
    public String getGENDER() {
        return GENDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.GENDER
     *
     * @param GENDER the value for TBL_JOBINFO.GENDER
     *
     * @mbggenerated
     */
    public void setGENDER(String GENDER) {
        this.GENDER = GENDER == null ? null : GENDER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.NATIONALITY
     *
     * @return the value of TBL_JOBINFO.NATIONALITY
     *
     * @mbggenerated
     */
    public String getNATIONALITY() {
        return NATIONALITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.NATIONALITY
     *
     * @param NATIONALITY the value for TBL_JOBINFO.NATIONALITY
     *
     * @mbggenerated
     */
    public void setNATIONALITY(String NATIONALITY) {
        this.NATIONALITY = NATIONALITY == null ? null : NATIONALITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.AGE
     *
     * @return the value of TBL_JOBINFO.AGE
     *
     * @mbggenerated
     */
    public String getAGE() {
        return AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.AGE
     *
     * @param AGE the value for TBL_JOBINFO.AGE
     *
     * @mbggenerated
     */
    public void setAGE(String AGE) {
        this.AGE = AGE == null ? null : AGE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.MARRAGE
     *
     * @return the value of TBL_JOBINFO.MARRAGE
     *
     * @mbggenerated
     */
    public BigDecimal getMARRAGE() {
        return MARRAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.MARRAGE
     *
     * @param MARRAGE the value for TBL_JOBINFO.MARRAGE
     *
     * @mbggenerated
     */
    public void setMARRAGE(BigDecimal MARRAGE) {
        this.MARRAGE = MARRAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.BIRTHDAY
     *
     * @return the value of TBL_JOBINFO.BIRTHDAY
     *
     * @mbggenerated
     */
    public String getBIRTHDAY() {
        return BIRTHDAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.BIRTHDAY
     *
     * @param BIRTHDAY the value for TBL_JOBINFO.BIRTHDAY
     *
     * @mbggenerated
     */
    public void setBIRTHDAY(String BIRTHDAY) {
        this.BIRTHDAY = BIRTHDAY == null ? null : BIRTHDAY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.BIRTHPLACE
     *
     * @return the value of TBL_JOBINFO.BIRTHPLACE
     *
     * @mbggenerated
     */
    public String getBIRTHPLACE() {
        return BIRTHPLACE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.BIRTHPLACE
     *
     * @param BIRTHPLACE the value for TBL_JOBINFO.BIRTHPLACE
     *
     * @mbggenerated
     */
    public void setBIRTHPLACE(String BIRTHPLACE) {
        this.BIRTHPLACE = BIRTHPLACE == null ? null : BIRTHPLACE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.PHOTOPATH
     *
     * @return the value of TBL_JOBINFO.PHOTOPATH
     *
     * @mbggenerated
     */
    public String getPHOTOPATH() {
        return PHOTOPATH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.PHOTOPATH
     *
     * @param PHOTOPATH the value for TBL_JOBINFO.PHOTOPATH
     *
     * @mbggenerated
     */
    public void setPHOTOPATH(String PHOTOPATH) {
        this.PHOTOPATH = PHOTOPATH == null ? null : PHOTOPATH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.PHOTOOLDNAME
     *
     * @return the value of TBL_JOBINFO.PHOTOOLDNAME
     *
     * @mbggenerated
     */
    public String getPHOTOOLDNAME() {
        return PHOTOOLDNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.PHOTOOLDNAME
     *
     * @param PHOTOOLDNAME the value for TBL_JOBINFO.PHOTOOLDNAME
     *
     * @mbggenerated
     */
    public void setPHOTOOLDNAME(String PHOTOOLDNAME) {
        this.PHOTOOLDNAME = PHOTOOLDNAME == null ? null : PHOTOOLDNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.ACCONTPLACE
     *
     * @return the value of TBL_JOBINFO.ACCONTPLACE
     *
     * @mbggenerated
     */
    public String getACCONTPLACE() {
        return ACCONTPLACE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.ACCONTPLACE
     *
     * @param ACCONTPLACE the value for TBL_JOBINFO.ACCONTPLACE
     *
     * @mbggenerated
     */
    public void setACCONTPLACE(String ACCONTPLACE) {
        this.ACCONTPLACE = ACCONTPLACE == null ? null : ACCONTPLACE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.HOMEADDRESS
     *
     * @return the value of TBL_JOBINFO.HOMEADDRESS
     *
     * @mbggenerated
     */
    public String getHOMEADDRESS() {
        return HOMEADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.HOMEADDRESS
     *
     * @param HOMEADDRESS the value for TBL_JOBINFO.HOMEADDRESS
     *
     * @mbggenerated
     */
    public void setHOMEADDRESS(String HOMEADDRESS) {
        this.HOMEADDRESS = HOMEADDRESS == null ? null : HOMEADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.LIVEADDRESS
     *
     * @return the value of TBL_JOBINFO.LIVEADDRESS
     *
     * @mbggenerated
     */
    public String getLIVEADDRESS() {
        return LIVEADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.LIVEADDRESS
     *
     * @param LIVEADDRESS the value for TBL_JOBINFO.LIVEADDRESS
     *
     * @mbggenerated
     */
    public void setLIVEADDRESS(String LIVEADDRESS) {
        this.LIVEADDRESS = LIVEADDRESS == null ? null : LIVEADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.EDUCATIONALCATEGORIE
     *
     * @return the value of TBL_JOBINFO.EDUCATIONALCATEGORIE
     *
     * @mbggenerated
     */
    public String getEDUCATIONALCATEGORIE() {
        return EDUCATIONALCATEGORIE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.EDUCATIONALCATEGORIE
     *
     * @param EDUCATIONALCATEGORIE the value for TBL_JOBINFO.EDUCATIONALCATEGORIE
     *
     * @mbggenerated
     */
    public void setEDUCATIONALCATEGORIE(String EDUCATIONALCATEGORIE) {
        this.EDUCATIONALCATEGORIE = EDUCATIONALCATEGORIE == null ? null : EDUCATIONALCATEGORIE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.EDUCATION
     *
     * @return the value of TBL_JOBINFO.EDUCATION
     *
     * @mbggenerated
     */
    public String getEDUCATION() {
        return EDUCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.EDUCATION
     *
     * @param EDUCATION the value for TBL_JOBINFO.EDUCATION
     *
     * @mbggenerated
     */
    public void setEDUCATION(String EDUCATION) {
        this.EDUCATION = EDUCATION == null ? null : EDUCATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.MAJORSUBJECTS1
     *
     * @return the value of TBL_JOBINFO.MAJORSUBJECTS1
     *
     * @mbggenerated
     */
    public String getMAJORSUBJECTS1() {
        return MAJORSUBJECTS1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.MAJORSUBJECTS1
     *
     * @param MAJORSUBJECTS1 the value for TBL_JOBINFO.MAJORSUBJECTS1
     *
     * @mbggenerated
     */
    public void setMAJORSUBJECTS1(String MAJORSUBJECTS1) {
        this.MAJORSUBJECTS1 = MAJORSUBJECTS1 == null ? null : MAJORSUBJECTS1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.MAJORSUBJECTS2
     *
     * @return the value of TBL_JOBINFO.MAJORSUBJECTS2
     *
     * @mbggenerated
     */
    public String getMAJORSUBJECTS2() {
        return MAJORSUBJECTS2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.MAJORSUBJECTS2
     *
     * @param MAJORSUBJECTS2 the value for TBL_JOBINFO.MAJORSUBJECTS2
     *
     * @mbggenerated
     */
    public void setMAJORSUBJECTS2(String MAJORSUBJECTS2) {
        this.MAJORSUBJECTS2 = MAJORSUBJECTS2 == null ? null : MAJORSUBJECTS2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.PROFESSIONAL
     *
     * @return the value of TBL_JOBINFO.PROFESSIONAL
     *
     * @mbggenerated
     */
    public String getPROFESSIONAL() {
        return PROFESSIONAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.PROFESSIONAL
     *
     * @param PROFESSIONAL the value for TBL_JOBINFO.PROFESSIONAL
     *
     * @mbggenerated
     */
    public void setPROFESSIONAL(String PROFESSIONAL) {
        this.PROFESSIONAL = PROFESSIONAL == null ? null : PROFESSIONAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.CERTIFICATE
     *
     * @return the value of TBL_JOBINFO.CERTIFICATE
     *
     * @mbggenerated
     */
    public String getCERTIFICATE() {
        return CERTIFICATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.CERTIFICATE
     *
     * @param CERTIFICATE the value for TBL_JOBINFO.CERTIFICATE
     *
     * @mbggenerated
     */
    public void setCERTIFICATE(String CERTIFICATE) {
        this.CERTIFICATE = CERTIFICATE == null ? null : CERTIFICATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.CBGNTIME
     *
     * @return the value of TBL_JOBINFO.CBGNTIME
     *
     * @mbggenerated
     */
    public String getCBGNTIME() {
        return CBGNTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.CBGNTIME
     *
     * @param CBGNTIME the value for TBL_JOBINFO.CBGNTIME
     *
     * @mbggenerated
     */
    public void setCBGNTIME(String CBGNTIME) {
        this.CBGNTIME = CBGNTIME == null ? null : CBGNTIME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.CENDTIME
     *
     * @return the value of TBL_JOBINFO.CENDTIME
     *
     * @mbggenerated
     */
    public String getCENDTIME() {
        return CENDTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.CENDTIME
     *
     * @param CENDTIME the value for TBL_JOBINFO.CENDTIME
     *
     * @mbggenerated
     */
    public void setCENDTIME(String CENDTIME) {
        this.CENDTIME = CENDTIME == null ? null : CENDTIME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.GRADUATESCHOOL
     *
     * @return the value of TBL_JOBINFO.GRADUATESCHOOL
     *
     * @mbggenerated
     */
    public String getGRADUATESCHOOL() {
        return GRADUATESCHOOL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.GRADUATESCHOOL
     *
     * @param GRADUATESCHOOL the value for TBL_JOBINFO.GRADUATESCHOOL
     *
     * @mbggenerated
     */
    public void setGRADUATESCHOOL(String GRADUATESCHOOL) {
        this.GRADUATESCHOOL = GRADUATESCHOOL == null ? null : GRADUATESCHOOL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.DOCUMENTSTYPE
     *
     * @return the value of TBL_JOBINFO.DOCUMENTSTYPE
     *
     * @mbggenerated
     */
    public String getDOCUMENTSTYPE() {
        return DOCUMENTSTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.DOCUMENTSTYPE
     *
     * @param DOCUMENTSTYPE the value for TBL_JOBINFO.DOCUMENTSTYPE
     *
     * @mbggenerated
     */
    public void setDOCUMENTSTYPE(String DOCUMENTSTYPE) {
        this.DOCUMENTSTYPE = DOCUMENTSTYPE == null ? null : DOCUMENTSTYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.DOCUMENTSNUM1
     *
     * @return the value of TBL_JOBINFO.DOCUMENTSNUM1
     *
     * @mbggenerated
     */
    public String getDOCUMENTSNUM1() {
        return DOCUMENTSNUM1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.DOCUMENTSNUM1
     *
     * @param DOCUMENTSNUM1 the value for TBL_JOBINFO.DOCUMENTSNUM1
     *
     * @mbggenerated
     */
    public void setDOCUMENTSNUM1(String DOCUMENTSNUM1) {
        this.DOCUMENTSNUM1 = DOCUMENTSNUM1 == null ? null : DOCUMENTSNUM1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.TITLEBGNTIME
     *
     * @return the value of TBL_JOBINFO.TITLEBGNTIME
     *
     * @mbggenerated
     */
    public String getTITLEBGNTIME() {
        return TITLEBGNTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.TITLEBGNTIME
     *
     * @param TITLEBGNTIME the value for TBL_JOBINFO.TITLEBGNTIME
     *
     * @mbggenerated
     */
    public void setTITLEBGNTIME(String TITLEBGNTIME) {
        this.TITLEBGNTIME = TITLEBGNTIME == null ? null : TITLEBGNTIME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.TITLENAME
     *
     * @return the value of TBL_JOBINFO.TITLENAME
     *
     * @mbggenerated
     */
    public String getTITLENAME() {
        return TITLENAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.TITLENAME
     *
     * @param TITLENAME the value for TBL_JOBINFO.TITLENAME
     *
     * @mbggenerated
     */
    public void setTITLENAME(String TITLENAME) {
        this.TITLENAME = TITLENAME == null ? null : TITLENAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.GRADE
     *
     * @return the value of TBL_JOBINFO.GRADE
     *
     * @mbggenerated
     */
    public String getGRADE() {
        return GRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.GRADE
     *
     * @param GRADE the value for TBL_JOBINFO.GRADE
     *
     * @mbggenerated
     */
    public void setGRADE(String GRADE) {
        this.GRADE = GRADE == null ? null : GRADE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.WORKBGNTIME1
     *
     * @return the value of TBL_JOBINFO.WORKBGNTIME1
     *
     * @mbggenerated
     */
    public String getWORKBGNTIME1() {
        return WORKBGNTIME1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.WORKBGNTIME1
     *
     * @param WORKBGNTIME1 the value for TBL_JOBINFO.WORKBGNTIME1
     *
     * @mbggenerated
     */
    public void setWORKBGNTIME1(String WORKBGNTIME1) {
        this.WORKBGNTIME1 = WORKBGNTIME1 == null ? null : WORKBGNTIME1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.WORKENDTIME1
     *
     * @return the value of TBL_JOBINFO.WORKENDTIME1
     *
     * @mbggenerated
     */
    public String getWORKENDTIME1() {
        return WORKENDTIME1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.WORKENDTIME1
     *
     * @param WORKENDTIME1 the value for TBL_JOBINFO.WORKENDTIME1
     *
     * @mbggenerated
     */
    public void setWORKENDTIME1(String WORKENDTIME1) {
        this.WORKENDTIME1 = WORKENDTIME1 == null ? null : WORKENDTIME1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.EMPLOYER1
     *
     * @return the value of TBL_JOBINFO.EMPLOYER1
     *
     * @mbggenerated
     */
    public String getEMPLOYER1() {
        return EMPLOYER1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.EMPLOYER1
     *
     * @param EMPLOYER1 the value for TBL_JOBINFO.EMPLOYER1
     *
     * @mbggenerated
     */
    public void setEMPLOYER1(String EMPLOYER1) {
        this.EMPLOYER1 = EMPLOYER1 == null ? null : EMPLOYER1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.POST1
     *
     * @return the value of TBL_JOBINFO.POST1
     *
     * @mbggenerated
     */
    public String getPOST1() {
        return POST1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.POST1
     *
     * @param POST1 the value for TBL_JOBINFO.POST1
     *
     * @mbggenerated
     */
    public void setPOST1(String POST1) {
        this.POST1 = POST1 == null ? null : POST1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.CITY1
     *
     * @return the value of TBL_JOBINFO.CITY1
     *
     * @mbggenerated
     */
    public String getCITY1() {
        return CITY1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.CITY1
     *
     * @param CITY1 the value for TBL_JOBINFO.CITY1
     *
     * @mbggenerated
     */
    public void setCITY1(String CITY1) {
        this.CITY1 = CITY1 == null ? null : CITY1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.MOBILE
     *
     * @return the value of TBL_JOBINFO.MOBILE
     *
     * @mbggenerated
     */
    public String getMOBILE() {
        return MOBILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.MOBILE
     *
     * @param MOBILE the value for TBL_JOBINFO.MOBILE
     *
     * @mbggenerated
     */
    public void setMOBILE(String MOBILE) {
        this.MOBILE = MOBILE == null ? null : MOBILE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.PHONE
     *
     * @return the value of TBL_JOBINFO.PHONE
     *
     * @mbggenerated
     */
    public String getPHONE() {
        return PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.PHONE
     *
     * @param PHONE the value for TBL_JOBINFO.PHONE
     *
     * @mbggenerated
     */
    public void setPHONE(String PHONE) {
        this.PHONE = PHONE == null ? null : PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.EMAIL
     *
     * @return the value of TBL_JOBINFO.EMAIL
     *
     * @mbggenerated
     */
    public String getEMAIL() {
        return EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.EMAIL
     *
     * @param EMAIL the value for TBL_JOBINFO.EMAIL
     *
     * @mbggenerated
     */
    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL == null ? null : EMAIL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.CREATEDATE
     *
     * @return the value of TBL_JOBINFO.CREATEDATE
     *
     * @mbggenerated
     */
    public Date getCREATEDATE() {
        return CREATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.CREATEDATE
     *
     * @param CREATEDATE the value for TBL_JOBINFO.CREATEDATE
     *
     * @mbggenerated
     */
    public void setCREATEDATE(Date CREATEDATE) {
        this.CREATEDATE = CREATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.MAJOR1
     *
     * @return the value of TBL_JOBINFO.MAJOR1
     *
     * @mbggenerated
     */
    public String getMAJOR1() {
        return MAJOR1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.MAJOR1
     *
     * @param MAJOR1 the value for TBL_JOBINFO.MAJOR1
     *
     * @mbggenerated
     */
    public void setMAJOR1(String MAJOR1) {
        this.MAJOR1 = MAJOR1 == null ? null : MAJOR1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.MAJOR2
     *
     * @return the value of TBL_JOBINFO.MAJOR2
     *
     * @mbggenerated
     */
    public String getMAJOR2() {
        return MAJOR2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.MAJOR2
     *
     * @param MAJOR2 the value for TBL_JOBINFO.MAJOR2
     *
     * @mbggenerated
     */
    public void setMAJOR2(String MAJOR2) {
        this.MAJOR2 = MAJOR2 == null ? null : MAJOR2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.DOCUMENTSNUM2
     *
     * @return the value of TBL_JOBINFO.DOCUMENTSNUM2
     *
     * @mbggenerated
     */
    public String getDOCUMENTSNUM2() {
        return DOCUMENTSNUM2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.DOCUMENTSNUM2
     *
     * @param DOCUMENTSNUM2 the value for TBL_JOBINFO.DOCUMENTSNUM2
     *
     * @mbggenerated
     */
    public void setDOCUMENTSNUM2(String DOCUMENTSNUM2) {
        this.DOCUMENTSNUM2 = DOCUMENTSNUM2 == null ? null : DOCUMENTSNUM2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.DOCUMENTSNUM3
     *
     * @return the value of TBL_JOBINFO.DOCUMENTSNUM3
     *
     * @mbggenerated
     */
    public String getDOCUMENTSNUM3() {
        return DOCUMENTSNUM3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.DOCUMENTSNUM3
     *
     * @param DOCUMENTSNUM3 the value for TBL_JOBINFO.DOCUMENTSNUM3
     *
     * @mbggenerated
     */
    public void setDOCUMENTSNUM3(String DOCUMENTSNUM3) {
        this.DOCUMENTSNUM3 = DOCUMENTSNUM3 == null ? null : DOCUMENTSNUM3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.DOCUMENTSNUM4
     *
     * @return the value of TBL_JOBINFO.DOCUMENTSNUM4
     *
     * @mbggenerated
     */
    public String getDOCUMENTSNUM4() {
        return DOCUMENTSNUM4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.DOCUMENTSNUM4
     *
     * @param DOCUMENTSNUM4 the value for TBL_JOBINFO.DOCUMENTSNUM4
     *
     * @mbggenerated
     */
    public void setDOCUMENTSNUM4(String DOCUMENTSNUM4) {
        this.DOCUMENTSNUM4 = DOCUMENTSNUM4 == null ? null : DOCUMENTSNUM4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.WORKBGNTIME2
     *
     * @return the value of TBL_JOBINFO.WORKBGNTIME2
     *
     * @mbggenerated
     */
    public String getWORKBGNTIME2() {
        return WORKBGNTIME2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.WORKBGNTIME2
     *
     * @param WORKBGNTIME2 the value for TBL_JOBINFO.WORKBGNTIME2
     *
     * @mbggenerated
     */
    public void setWORKBGNTIME2(String WORKBGNTIME2) {
        this.WORKBGNTIME2 = WORKBGNTIME2 == null ? null : WORKBGNTIME2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.WORKENDTIME2
     *
     * @return the value of TBL_JOBINFO.WORKENDTIME2
     *
     * @mbggenerated
     */
    public String getWORKENDTIME2() {
        return WORKENDTIME2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.WORKENDTIME2
     *
     * @param WORKENDTIME2 the value for TBL_JOBINFO.WORKENDTIME2
     *
     * @mbggenerated
     */
    public void setWORKENDTIME2(String WORKENDTIME2) {
        this.WORKENDTIME2 = WORKENDTIME2 == null ? null : WORKENDTIME2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.EMPLOYER2
     *
     * @return the value of TBL_JOBINFO.EMPLOYER2
     *
     * @mbggenerated
     */
    public String getEMPLOYER2() {
        return EMPLOYER2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.EMPLOYER2
     *
     * @param EMPLOYER2 the value for TBL_JOBINFO.EMPLOYER2
     *
     * @mbggenerated
     */
    public void setEMPLOYER2(String EMPLOYER2) {
        this.EMPLOYER2 = EMPLOYER2 == null ? null : EMPLOYER2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.POST2
     *
     * @return the value of TBL_JOBINFO.POST2
     *
     * @mbggenerated
     */
    public String getPOST2() {
        return POST2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.POST2
     *
     * @param POST2 the value for TBL_JOBINFO.POST2
     *
     * @mbggenerated
     */
    public void setPOST2(String POST2) {
        this.POST2 = POST2 == null ? null : POST2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.CITY2
     *
     * @return the value of TBL_JOBINFO.CITY2
     *
     * @mbggenerated
     */
    public String getCITY2() {
        return CITY2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.CITY2
     *
     * @param CITY2 the value for TBL_JOBINFO.CITY2
     *
     * @mbggenerated
     */
    public void setCITY2(String CITY2) {
        this.CITY2 = CITY2 == null ? null : CITY2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.WORKBGNTIME3
     *
     * @return the value of TBL_JOBINFO.WORKBGNTIME3
     *
     * @mbggenerated
     */
    public String getWORKBGNTIME3() {
        return WORKBGNTIME3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.WORKBGNTIME3
     *
     * @param WORKBGNTIME3 the value for TBL_JOBINFO.WORKBGNTIME3
     *
     * @mbggenerated
     */
    public void setWORKBGNTIME3(String WORKBGNTIME3) {
        this.WORKBGNTIME3 = WORKBGNTIME3 == null ? null : WORKBGNTIME3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.WORKENDTIME3
     *
     * @return the value of TBL_JOBINFO.WORKENDTIME3
     *
     * @mbggenerated
     */
    public String getWORKENDTIME3() {
        return WORKENDTIME3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.WORKENDTIME3
     *
     * @param WORKENDTIME3 the value for TBL_JOBINFO.WORKENDTIME3
     *
     * @mbggenerated
     */
    public void setWORKENDTIME3(String WORKENDTIME3) {
        this.WORKENDTIME3 = WORKENDTIME3 == null ? null : WORKENDTIME3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.EMPLOYER3
     *
     * @return the value of TBL_JOBINFO.EMPLOYER3
     *
     * @mbggenerated
     */
    public String getEMPLOYER3() {
        return EMPLOYER3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.EMPLOYER3
     *
     * @param EMPLOYER3 the value for TBL_JOBINFO.EMPLOYER3
     *
     * @mbggenerated
     */
    public void setEMPLOYER3(String EMPLOYER3) {
        this.EMPLOYER3 = EMPLOYER3 == null ? null : EMPLOYER3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.POST3
     *
     * @return the value of TBL_JOBINFO.POST3
     *
     * @mbggenerated
     */
    public String getPOST3() {
        return POST3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.POST3
     *
     * @param POST3 the value for TBL_JOBINFO.POST3
     *
     * @mbggenerated
     */
    public void setPOST3(String POST3) {
        this.POST3 = POST3 == null ? null : POST3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.CITY3
     *
     * @return the value of TBL_JOBINFO.CITY3
     *
     * @mbggenerated
     */
    public String getCITY3() {
        return CITY3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.CITY3
     *
     * @param CITY3 the value for TBL_JOBINFO.CITY3
     *
     * @mbggenerated
     */
    public void setCITY3(String CITY3) {
        this.CITY3 = CITY3 == null ? null : CITY3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_JOBINFO.SUBTITLENAME
     *
     * @return the value of TBL_JOBINFO.SUBTITLENAME
     *
     * @mbggenerated
     */
    public String getSUBTITLENAME() {
        return SUBTITLENAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_JOBINFO.SUBTITLENAME
     *
     * @param SUBTITLENAME the value for TBL_JOBINFO.SUBTITLENAME
     *
     * @mbggenerated
     */
    public void setSUBTITLENAME(String SUBTITLENAME) {
        this.SUBTITLENAME = SUBTITLENAME == null ? null : SUBTITLENAME.trim();
    }
}